<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>WhisperAttackServerCommand</RootNamespace>
    <AssemblyName>WhisperAttack</AssemblyName>
  </PropertyGroup>
</Project>
